/**
 * Save a finalized transcript (transcript_chunks) onto a recording row.
 *
 * POST /api/sermons/save-transcript
 *   { recordingId: string, chunks: TranscriptChunk[] }
 *
 * Used by the client after multi-chunk Whisper transcription so we don't have
 * to re-upload the original audio. Only the `transcript_chunks` column is
 * updated — the audio file in Supabase Storage is never touched.
 */

import { NextRequest, NextResponse } from "next/server";
import { createClient } from "@supabase/supabase-js";

export const runtime = "nodejs";

interface IncomingChunk {
  text: string;
  timestampMs: number;
  isFinal?: boolean;
  speaker?: string;
  speakerTag?: boolean;
  source?: "whisper" | "whisper-live";
}

export async function POST(request: NextRequest) {
  try {
    const authHeader = request.headers.get("authorization");
    const token = authHeader?.startsWith("Bearer ") ? authHeader.substring(7) : null;
    if (!token) {
      return NextResponse.json(
        { error: "Unauthorized", message: "You must be logged in to save a transcript" },
        { status: 401 }
      );
    }

    const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL || "";
    const supabaseAnonKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY || "";
    if (!supabaseUrl || !supabaseAnonKey) {
      return NextResponse.json(
        { error: "Server configuration error", message: "Supabase not configured" },
        { status: 500 }
      );
    }

    const supabase = createClient(supabaseUrl, supabaseAnonKey, {
      auth: { persistSession: false, autoRefreshToken: false },
      global: { headers: { Authorization: `Bearer ${token}` } },
    });

    const { data: { user }, error: authError } = await supabase.auth.getUser(token);
    if (authError || !user) {
      return NextResponse.json(
        { error: "Unauthorized", message: "You must be logged in to save a transcript" },
        { status: 401 }
      );
    }

    const body = await request.json().catch(() => ({}));
    const recordingId = body?.recordingId as string | undefined;
    const incoming = body?.chunks as IncomingChunk[] | undefined;

    if (!recordingId || !Array.isArray(incoming)) {
      return NextResponse.json(
        { error: "Bad request", message: "recordingId and chunks[] are required" },
        { status: 400 }
      );
    }

    // Pull existing chunks so we can preserve speaker tags coming from
    // the live recorder (they're not regenerated by Whisper).
    const { data: existing, error: fetchError } = await supabase
      .from("recordings")
      .select("transcript_chunks")
      .eq("id", recordingId)
      .eq("user_id", user.id)
      .maybeSingle();

    if (fetchError) {
      return NextResponse.json(
        { error: "Database error", message: fetchError.message },
        { status: 500 }
      );
    }
    if (!existing) {
      return NextResponse.json(
        { error: "Not found", message: "Recording not found or not owned by current user" },
        { status: 404 }
      );
    }

    const existingChunks: IncomingChunk[] = Array.isArray(existing.transcript_chunks)
      ? existing.transcript_chunks
      : [];

    const speakerTagChunks = existingChunks.filter((c) => c?.speakerTag === true);

    const cleaned = incoming
      .filter((c) => c && typeof c.text === "string" && c.text.trim().length > 0)
      .map((c) => ({
        text: c.text.trim(),
        timestampMs: Math.max(0, Math.floor(c.timestampMs || 0)),
        isFinal: c.isFinal !== false,
        speaker: c.speaker,
        speakerTag: c.speakerTag === true,
        source: c.source || "whisper",
      }));

    const merged = [...cleaned, ...speakerTagChunks].sort(
      (a, b) => (a.timestampMs || 0) - (b.timestampMs || 0)
    );

    const { error: updateError } = await supabase
      .from("recordings")
      .update({ transcript_chunks: merged })
      .eq("id", recordingId)
      .eq("user_id", user.id);

    if (updateError) {
      return NextResponse.json(
        { error: "Database error", message: updateError.message },
        { status: 500 }
      );
    }

    return NextResponse.json({ success: true, chunks: merged });
  } catch (error) {
    console.error("Save-transcript API error:", error);
    return NextResponse.json(
      {
        error: "Save failed",
        message: error instanceof Error ? error.message : "Unknown error",
      },
      { status: 500 }
    );
  }
}
